require: rubocop-rails

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false